services:
  
  order-db:
    image: mongo:latest
    container_name: order-db
    restart: always
    networks:
      - orchestrator-saga
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
  
  product-db:
    container_name: product-db
    image: postgres:latest
    environment:
      POSTGRES_DB: product-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5432:5432"
  
  payment-db:
    container_name: payment-db
    image: postgres:latest
    environment:
      POSTGRES_DB: payment-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5433:5432"
  
  inventory-db:
    container_name: inventory-db
    image: postgres:latest
    environment:
      POSTGRES_DB: inventory-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - orchestrator-saga
    ports:
      - "5434:5432"

  mongo-express:
    image: mongo-express:latest
    restart: always
    container_name: mongo_ui
    networks:
      - orchestrator-saga
    ports:
      - 18080:8081
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:123456@order-db:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - order-db

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: "no"
    ports:
      - "9092:9092"
    networks:
      - orchestrator-saga
    environment:
      # Configurações do Cluster e KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'

      # Listeners (Onde o Kafka ouve)
      # 9092 para fora do Docker, 29092 para dentro da rede Docker, 29093 para o controle interno
      KAFKA_LISTENERS: 'EXTERNAL://:9092,INTERNAL://:29092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'EXTERNAL://localhost:9092,INTERNAL://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      # Outras configs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - ./data/kafka/data:/var/lib/kafka/data

  redpanda-console:
    container_name: redpanda
    image: redpandadata/console:latest
    restart: on-failure
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    ports:
      - "8081:8080"
    networks:
      - orchestrator-saga
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["kafka:29092"]
    depends_on:
      - "kafka"

#  order-service:
#    build: './OrderService'
#    container_name: order-service
#    depends_on:
#      - order-db
#      - kafka
#    networks:
#      - orchestrator-saga
#    environment:
#      - KAFKA_BROKER=kafka:29092
#      - MONGO_DB_URI=mongodb://admin:123456@order-db:27017
#    ports:
#      - 3000:3000
#
#  orchestrator-service:
#    build: './OrchestratorService'
#    container_name: orchestrator-service
#    depends_on:
#      - kafka
#    networks:
#      - orchestrator-saga
#    environment:
#      - KAFKA_BROKER=kafka:29092
#    ports:
#      - 8080:8080
#
#  product-validation-service:
#    build: './ProductValidationService'
#    container_name: product-validation-service
#    depends_on:
#      - product-db
#      - kafka
#    networks:
#      - orchestrator-saga
#    environment:
#      - KAFKA_BROKER=kafka:29092
#      - DB_HOST=product-db
#      - DB_PORT=5432
#      - DB_NAME=product-db
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#    ports:
#      - 8090:8090
#
#  payment-service:
#    build: './PaymentService'
#    container_name: payment-service
#    depends_on:
#      - payment-db
#      - kafka
#    networks:
#      - orchestrator-saga
#    environment:
#      - KAFKA_BROKER=kafka:29092
#      - DB_HOST=payment-db
#      - DB_PORT=5432
#      - DB_NAME=payment-db
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#    ports:
#      - 8091:8091
#
#  inventory-service:
#    build: './InventoryService'
#    container_name: inventory-service
#    depends_on:
#      - inventory-db
#      - kafka
#    networks:
#      - orchestrator-saga
#    environment:
#      - KAFKA_BROKER=kafka:29092
#      - DB_HOST=inventory-db
#      - DB_PORT=5432
#      - DB_NAME=inventory-db
#      - DB_USER=postgres
#      - DB_PASSWORD=postgres
#    ports:
#      - 8092:8092

networks:
  orchestrator-saga:
    driver: bridge