app:
  kafka:
    topic:
      start-saga: start-saga
      notify-ending: notify-ending
    topic-config:
      partitions: 1
      replicas: 1

server:
  port: 3000

logging:
  level:
    org:
      apache:
        kafka: INFO