app:
  kafka:
    topic:
      start-saga: start-saga
      orchestrator: orchestrator
      finish-success: finish-success
      finish-fail: finish-fail

    topic-config:
      partitions: 1
      replicas: 1

server:
  port: 8080

logging:
  level:
    org:
      apache:
        kafka: OFF