spring:
  application:
    name: ProductValidationService

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/product-db?createDatabaseIfNotExist=true
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8090
